@spiderVoodoo_HostAddress = http://localhost:5273
# @name login
POST {{spiderVoodoo_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
     "email": "testuser@example.com",
     "password": "Test@1234"
}
###
@spiderVoodoo_AccessToken = {{login.response.body.token}} 
###
POST {{spiderVoodoo_HostAddress}}/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{spiderVoodoo_AccessToken}}

{
     "username": "testuser",
     "password": "Test@1234",
     "email": "testuser@example.com"
}
###
@user_id = 
GET {{spiderVoodoo_HostAddress}}/users/{{user_id}}
Accept: application/json
###